### ISSUE TITLE
Register and tag?

### ISSUE THREAD

**Issue by sbromberger** [JeffreySarnoff/CardinalDicts.jl#1]
Jeffrey,

I have a possible immediate need for this package in LightGraphs. Could I ask you to register and tag this in METADATA so I can include it as a dependency?

**Comment by JeffreySarnoff** [comment]
It has been merged with tag v0.0.1.  I am glad that you have use for this work.

**Comment by sbromberger** [comment]
Found it! https://github.com/JuliaLang/METADATA.jl/pull/10506.  Thank you.

**Comment by JeffreySarnoff** [comment]
fyi v0.0.1 is pre-dict-doc review.  In the next release keymax is not exported, as Base.endof is included with that release.  Also, Base.delete! will replace clearindex! and clearindex! will clear the index without returning the dict.  I plan to release v0.1.0 (as not exporting keymax is a breaking change) with those changes and maybe CardinalDict{V1,V2}(n) supporting ordered pairs stored as separate vectors and set/getindex -> (V1,V2), set/getindex1 -> V1, set/getindex2 -> V2 while delete/clearindex applies to the pair.
