### ISSUE TITLE
Use github renaming functionality to move back to registered name

### ISSUE THREAD

**Issue by tkelman** [JeffreySarnoff/CardinalDicts.jl#3]
cc @JeffreySarnoff you seem to have deleted the old repository at https://github.com/JeffreySarnoff/CardinalDicts.jl, and pushed the code to a newly created repo here. That breaks `Pkg.add("CardinalDicts")`. I can fix it by pushing a copy to JuliaPackageMirrors and changing the METADATA url to point there, but would be better if you moved your own repo to its original name. Change the name of a registered package is complicated and should be done with care to avoid breaking anything. If you go to the settings and find the option to rename the repository, github will conveniently put in place redirects so some things will keep working.

**Comment by JeffreySarnoff** [comment]
giving it a try

**Comment by tkelman** [comment]
looks better thanks
